.gitignore, external-dns.go, main.go, metadata/handler.go, providers/provider.go, providers/route53.go
* don't log an error in the methods; propagate err to main and log there
* external-dns code to its own file
* register provider in main() instead of init()
=> Addressing review comments:

external-dns.go, main.go, metadata/handler.go
External dns is deployed on per environment, and handle dns update for all stacks under this environment
=> More review comments addressed

external-dns.go, metadata.go, providers/provider.go
https://github.com/rancher/rancher/issues/2546
=> Configurable TTL

Godeps/Godeps.json, Godeps/_workspace/src/github.com/weppos/go-dnsimple/LICENSE, Godeps/_workspace/src/github.com/weppos/go-dnsimple/dnsimple/contacts.go, Godeps/_workspace/src/github.com/weppos/go-dnsimple/dnsimple/dnsimple.go, Godeps/_workspace/src/github.com/weppos/go-dnsimple/dnsimple/domains.go, Godeps/_workspace/src/github.com/weppos/go-dnsimple/dnsimple/domains_records.go, Godeps/_workspace/src/github.com/weppos/go-dnsimple/dnsimple/domains_zones.go, Godeps/_workspace/src/github.com/weppos/go-dnsimple/dnsimple/registrar.go, Godeps/_workspace/src/github.com/weppos/go-dnsimple/dnsimple/users.go, providers/dnsimple.go, providers/route53.go
also tweaked the init function in the route53 handler so it doesn't cause the whole thing to error out if you're not using it
=> add dnsimple provider

Godeps/Godeps.json, Godeps/_workspace/src/github.com/crackcomm/cloudflare/.gitignore, Godeps/_workspace/src/github.com/crackcomm/cloudflare/LICENSE, Godeps/_workspace/src/github.com/crackcomm/cloudflare/README.md, Godeps/_workspace/src/github.com/crackcomm/cloudflare/client.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/client_api.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/client_records.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/client_records_test.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/client_zones.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/client_zones_test.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/messages.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/messages_records.go, Godeps/_workspace/src/github.com/crackcomm/cloudflare/messages_zones.go, Godeps/_workspace/src/golang.org/x/net/context/context.go, Godeps/_workspace/src/golang.org/x/net/context/context_test.go, Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/cancelreq.go, Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/cancelreq_go14.go, Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/ctxhttp.go, Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/ctxhttp_test.go, Godeps/_workspace/src/golang.org/x/net/context/withtimeout_test.go, providers/cloudflare.go
https://www.cloudflare.com/dns/
PR for adding this to the catalog: https://github.com/rancher/rancher-catalog/pull/49
Also needs a nice SVG logo.
=> Add Cloudflare DNS provider

Godeps/Godeps.json, Godeps/_workspace/src/github.com/cognetoapps/go-pointdns/.gitignore, Godeps/_workspace/src/github.com/cognetoapps/go-pointdns/LICENSE, Godeps/_workspace/src/github.com/cognetoapps/go-pointdns/README.md, Godeps/_workspace/src/github.com/cognetoapps/go-pointdns/pointdns.go, Godeps/_workspace/src/github.com/cognetoapps/go-pointdns/record.go, Godeps/_workspace/src/github.com/cognetoapps/go-pointdns/zone.go, providers/pointhq.go
This add support for using PointHQ for managing automated DNS from Rancher.
=> Add support for PointHQ DNS

Godeps/Godeps.json, Godeps/_workspace/src/github.com/juju/ratelimit/LICENSE, Godeps/_workspace/src/github.com/juju/ratelimit/README.md, Godeps/_workspace/src/github.com/juju/ratelimit/ratelimit.go, Godeps/_workspace/src/github.com/juju/ratelimit/ratelimit_test.go, external-dns.go, providers/route53.go
Fixes https://github.com/rancher/rancher/issues/3257
/cc @alena1108
=> Throttle Route53 API calls

providers/route53.go
https://github.com/rancher/rancher/issues/4582
=> Route 53: Validate hosted zone ID on startup

Godeps/Godeps.json, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/client/default_retryer.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/config.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/corehandlers/param_validator.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/static_provider.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/http_request.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/http_request_1_4.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/validation.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/session/session.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/version.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go, Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/route53/api.go, providers/route53.go
Follow-up to https://github.com/rancher/rancher/issues/3257
=> route53: Update AWS SDK to v1.1.25; Raise max retries

Godeps/Godeps.json, Godeps/_workspace/src/github.com/rancher/go-rancher-metadata/metadata/metadata.go, Godeps/_workspace/src/github.com/rancher/go-rancher-metadata/metadata/types.go, metadata/metadata.go
WIP
see: https://github.com/rancher/rancher/issues/5143
Depends on:
=> Include only running/healthy containers

healthcheck.go, main.go, metadata/metadata.go, providers/dnsimple/dnsimple.go
Depends on https://github.com/rancher/external-dns/pull/46
=> Throttle DNSimple API calls

metadata/metadata.go
https://github.com/rancher/rancher/issues/6790
=> Don't create DNS records for system services

metadata/metadata.go
We needed more control over how external DNS was actually creating records, for example, we needed to be able to disable it on a per-host basis. We also needed to allow DNS entries to be made for containers that did not have ports exposed (but are reachable through our load-balancer).
Resolves rancher/rancher#7046
New Labels for Controlling External DNS. Notice that the label is to `disable` external DNS. This is so the current/original behavior is observed when the external DNS service is upgraded for existing deployments.
1. Host:      io.rancher.host.external_dns.disable=[default: no]
2. Service:   io.rancher.service.external_dns.disable=[default: no]
These two labels completely turn off external DNS at the host/service level.
3. Container: io.rancher.container.external_dns.force
This …
=> Added Support for Toggling DNS via Labels

main.go, providers/digitalocean/digitalocean.go, scripts/build
=> Fixes bug in DO provider that resulted in hundreds of orphaned records

main.go, providers/powerdns4/powerdns4.go
Support for powerdns provider is called powerdns4 uses the same details of powerdns provider
Closes rancher/rancher#6136
=> added support for powerdns4

providers/route53/route53.go
supersedes PR #68 
Also adds throttling API queries for paginated lists.
=> Add support for EC2 IAM role based authentication

package/Dockerfile, package/rancher-entrypoint.sh
https://github.com/rancher/rancher/issues/8284
=> Support for rancher server / load balancer using self-signed cert

providers/alidns/alidns.go
we need to use another query API now as Aliyun DNS API is returning a different format now
[issue](https://github.com/denverdino/aliyungo/issues/148)
=> use new Aliyun DNS query API

vendor.conf, vendor/github.com/prasmussen/gandi-api/domain/domain.go, vendor/github.com/prasmussen/gandi-api/domain/zone/record/record.go, vendor/github.com/prasmussen/gandi-api/domain/zone/record/structs.go, vendor/github.com/prasmussen/gandi-api/domain/zone/record/util.go
fix https://github.com/rancher/rancher/issues/10136
=> Upgrade gandi-api due to breaking change in zonerecord api

providers/infoblox/infoblox.go
https://github.com/rancher/rancher/issues/10117
https://gist.github.com/superseb/9bf843e6a2e82e8cf9f60ce350b7af82
=> Infoblox limits on healthcheck and zone

providers/dnsimple/dnsimple.go
=> Revert dns simple to v2 api

providers/infoblox/infoblox.go
This PR contains feats to infoblox provider:
- Pagination support to get more that 1000 entries by zone. https://github.com/rancher/rancher/issues/10317
- Updated url's to wapi v1.5 to support pagination. 
- Rancher secret support as an option to `INFOBLOX_PASSWORD` env variable. If `INFOBLOX_PASSWORD` is empty, will use `INFOBLOX_SECRET`.
=> Feat: Added pagination and secrets support to infoblox provider

package/Dockerfile, providers/rfc2136/rfc2136.go
https://github.com/rancher/rancher/issues/10135
image: janeczku/external-dns:fix-rfc2136-large
=> Fix issue with too large DNS messages
